services:
  backend:
    image: imagestreampi/api-infinitypay-java-prd:4
    container_name: api-infinity-pay
    restart: unless-stopped

    env_file:
      - .env

    environment:
      API_SPRING_KEY: ${API_SPRING_KEY}
      INFINITY_PAY_HANDLE: ${INFINITY_PAY_HANDLE}
      API_CORE_URL: ${API_CORE_URL}
      INFINITY_PAY_WEBHOOK_URL: ${INFINITY_PAY_WEBHOOK_URL}

    ports:
      - "8088:8088"



