# Nome da aplicacao
spring.config.import=optional:file:.env[.properties]

spring.application.name=payment-microservice

# Porta em que o microservico vai rodar
server.port=8088

# ==========================================
# INTEGRACOES EXTERNAS
# ==========================================

# URL do Backend (o principal que roda na porta 8080)
api.core.url=${API_CORE_URL:http://localhost:8080}

# Chave de seguranca para comunicar com o Backend
spring.api.key=${API_SPRING_KEY:CHAVE_PROVISORIA_DO_SPRING}

# Handle publico da Infinity Pay
infinity.pay.handle=${INFINITY_PAY_HANDLE:alexsander-torres}

# Endpoint publico que recebe as notificacoes de pagamento
infinity.pay.webhook-url=${INFINITY_PAY_WEBHOOK_URL:https://hurler-console-entrench.ngrok-free.dev/webhook}